name: CI

on: pull_request

jobs:
  build:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GIT_EMAIL: ${{ secrets.GIT_EMAIL}}
      GIT_USER: ${{ secrets.GIT_USER }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: npm install, start, and test
        run: |
          npm install yarn -g
          yarn --pure-lockfile
          lerna run start
